AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda Functions for POS System

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 10
    Environment:
      Variables:
        TABLE_NAME: 'products'

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: 'LambdaDynamoDBPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:Scan
                  - dynamodb:DeleteItem
                Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/products'

  # Lambda Function: Add Product
  AddProductFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: "lmb-add-product"
      CodeUri: src/
      Handler: add-product/index.handler
      Role: !GetAtt LambdaExecutionRole.Arn

  # Lambda Function: List Products
  ListProductsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: "lmb-list-products"
      CodeUri: src/
      Handler: list-products/index.handler
      Role: !GetAtt LambdaExecutionRole.Arn

  # Lambda Function: Delete Product
  DeleteProductFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: "lmb-delete-product"
      CodeUri: src/
      Handler: delete-product/index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
