AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda Functions for POS System

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 10
    Environment:
      Variables:
        TABLE_NAME: 'products'

Resources:
  # Lambda Function: Add Product
  AddProductFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: src/add-product/
      Handler: index.handler
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/products

  # Lambda Function: List Products
  ListProductsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: src/list-products/
      Handler: index.handler
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:Scan
            Resource: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/products

  # Lambda Function: Delete Product
  DeleteProductFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: src/delete-product/
      Handler: index.handler
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:DeleteItem
            Resource: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/products
