name: Deploy Lambda Functions
on:
  push:
    branches:
      - main
jobs:
  deploy-lambdas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Build and Deploy Lambdas
        run: |
          sam build
          sam deploy --stack-name pos-lambda-functions --resolve-s3 --capabilities CAPABILITY_IAM --force-upload
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
